### ISSUE TITLE
Can we add ipv6 lookup support?

### ISSUE THREAD

**Issue by qliu95114** [blrchen/azure-ip-lookup#1]
does azurespeed.com support ipv6 lookup?
2404:f801:18:40a:1ce9:1814:8483:2ab2

![image](https://user-images.githubusercontent.com/17083200/110566452-03da2f80-818b-11eb-8c4d-bb199e889054.png)

Add some ipv6 azure ip for validation testing
> Region: uscentral
> Resource: SQL Azure
> VIP -  DB  -  2603:10e1: 100:2::2845:bd30

**Comment by blrchen** [comment]
Here you go:
```
c:\>curl https://www.azurespeed.com/api/ipinfo?ipAddressOrUrl=2603:1030:0800:0005:0000:0000:BFEE:A418
{"serviceTagId":"AzureMonitor.SouthCentralUS","ipAddress":"2603:1030:0800:0005:0000:0000:BFEE:A418","ipAddressPrefix":"2603:1030:800:5::bfee:a418/128","region":"southcentralus","systemService":"AzureMonitor"}
```
